/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as StageEditorImport } from './routes/stage-editor'
import { Route as EntityEditorImport } from './routes/entity-editor'
import { Route as DisplayImport } from './routes/display'
import { Route as IndexImport } from './routes/index'
import { Route as ControlIdImport } from './routes/control.$id'

// Create/Update Routes

const StageEditorRoute = StageEditorImport.update({
  path: '/stage-editor',
  getParentRoute: () => rootRoute,
} as any)

const EntityEditorRoute = EntityEditorImport.update({
  path: '/entity-editor',
  getParentRoute: () => rootRoute,
} as any)

const DisplayRoute = DisplayImport.update({
  path: '/display',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ControlIdRoute = ControlIdImport.update({
  path: '/control/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/display': {
      id: '/display'
      path: '/display'
      fullPath: '/display'
      preLoaderRoute: typeof DisplayImport
      parentRoute: typeof rootRoute
    }
    '/entity-editor': {
      id: '/entity-editor'
      path: '/entity-editor'
      fullPath: '/entity-editor'
      preLoaderRoute: typeof EntityEditorImport
      parentRoute: typeof rootRoute
    }
    '/stage-editor': {
      id: '/stage-editor'
      path: '/stage-editor'
      fullPath: '/stage-editor'
      preLoaderRoute: typeof StageEditorImport
      parentRoute: typeof rootRoute
    }
    '/control/$id': {
      id: '/control/$id'
      path: '/control/$id'
      fullPath: '/control/$id'
      preLoaderRoute: typeof ControlIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/display': typeof DisplayRoute
  '/entity-editor': typeof EntityEditorRoute
  '/stage-editor': typeof StageEditorRoute
  '/control/$id': typeof ControlIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/display': typeof DisplayRoute
  '/entity-editor': typeof EntityEditorRoute
  '/stage-editor': typeof StageEditorRoute
  '/control/$id': typeof ControlIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/display': typeof DisplayRoute
  '/entity-editor': typeof EntityEditorRoute
  '/stage-editor': typeof StageEditorRoute
  '/control/$id': typeof ControlIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/display'
    | '/entity-editor'
    | '/stage-editor'
    | '/control/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/display' | '/entity-editor' | '/stage-editor' | '/control/$id'
  id:
    | '__root__'
    | '/'
    | '/display'
    | '/entity-editor'
    | '/stage-editor'
    | '/control/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DisplayRoute: typeof DisplayRoute
  EntityEditorRoute: typeof EntityEditorRoute
  StageEditorRoute: typeof StageEditorRoute
  ControlIdRoute: typeof ControlIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DisplayRoute: DisplayRoute,
  EntityEditorRoute: EntityEditorRoute,
  StageEditorRoute: StageEditorRoute,
  ControlIdRoute: ControlIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/display",
        "/entity-editor",
        "/stage-editor",
        "/control/$id"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/display": {
      "filePath": "display.tsx"
    },
    "/entity-editor": {
      "filePath": "entity-editor.tsx"
    },
    "/stage-editor": {
      "filePath": "stage-editor.tsx"
    },
    "/control/$id": {
      "filePath": "control.$id.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
